### ISSUE TITLE
ed25519: use from_bytes instead of from in ed25519 serde::Deserializer

### ISSUE THREAD

**Issue by ptrcnull** [RustCrypto/signatures#478]
Currently there's no way to catch the error when deserializing an invalid signature, because it uses `Signature::from` that panics:
https://github.com/RustCrypto/signatures/blob/e478469cece36a1275d80f644448b7cf1aae97d1/ed25519/src/lib.rs#L544-L546

**Comment by ptrcnull** [comment]
This seems to not have fixed the issue - as seen in the following stacktrace, `try_into` ends up calling the same `Signature::from`:
```
thread 'tokio-runtime-worker' panicked at 'invalid signature: signature::Error { source: None }', /home/demon/.cargo/registry/src/github.com-1ecc6299db9ec823/ed25519-1.5.1/src/lib.rs:332:38
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::result::unwrap_failed
   3: core::result::Result<T,E>::expect
             at /home/buildozer/aports/community/rust/src/rustc-1.60.0-src/library/core/src/result.rs:1022:23
   4: ed25519::Signature::new
             at /home/demon/.cargo/registry/src/github.com-1ecc6299db9ec823/ed25519-1.5.1/src/lib.rs:332:9
   5: <ed25519::Signature as core::convert::From<[u8; _]>>::from
             at /home/demon/.cargo/registry/src/github.com-1ecc6299db9ec823/ed25519-1.5.1/src/lib.rs:369:9
   6: <T as core::convert::Into<U>>::into
             at /home/buildozer/aports/community/rust/src/rustc-1.60.0-src/library/core/src/convert/mod.rs:546:9
   7: <T as core::convert::TryFrom<U>>::try_from
             at /home/buildozer/aports/community/rust/src/rustc-1.60.0-src/library/core/src/convert/mod.rs:601:12
   8: <T as core::convert::TryInto<U>>::try_into
             at /home/buildozer/aports/community/rust/src/rustc-1.60.0-src/library/core/src/convert/mod.rs:586:9
   9: <ed25519::Signature as serde::de::Deserialize>::deserialize::{{closure}}
             at /home/demon/.cargo/registry/src/github.com-1ecc6299db9ec823/ed25519-1.5.1/src/lib.rs:503:31
  10: core::result::Result<T,E>::and_then
             at /home/buildozer/aports/community/rust/src/rustc-1.60.0-src/library/core/src/result.rs:1311:22
  11: <ed25519::Signature as serde::de::Deserialize>::deserialize
             at /home/demon/.cargo/registry/src/github.com-1ecc6299db9ec823/ed25519-1.5.1/src/lib.rs:501:9
```

**Comment by aumetra** [comment]
`TryFrom` has a default implementation for every type that implements `From` (see [here](https://doc.rust-lang.org/stable/src/core/convert/mod.rs.html#590-603)).  
The change might use `.try_into()` now but it internally still calls the regular `From` implementation.

Rewriting the code as `(&bytes[..]).try_into().map_err(de::Error::custom)` should work

**Comment by tarcieri** [comment]
Alas, these serializers could use tests 😦 

I think I like your original suggestion of using `from_bytes`
